### ISSUE TITLE
Using datetime type in database date fields

### ISSUE THREAD

**Issue by msoa** [yeesoft/yii2-yee-post#3]
Why did you not use form `datetime` type in database date fields?

**Comment by yeesoft** [comment]
@msoa This is default type for [TimestampBehavior](http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html).

**Comment by msoa** [comment]
I think is better using **Bigint** instead **int** for database date fields (to avoiding  [2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem))
